const items = [
    {
      id: 1,
      title: 'classic summer shirt',
      category: 'AVAILABLE ITEMS',
      price: 15.99,
      img: './images.jfif',
      desc: `Made from cotton,good as a party wear`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'AVAILABLE ITEMS',
      price: 13.99,
      img: './images2.jfif',
      desc: `best for cold climates, goes well with boots`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'AVAILABLE ITEMS',
      price: 6.99,
      img: './images3.jfif',
      desc: `best for cold climates, goes well with boots`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'AVAILABLE ITEMS',
      price: 20.99,
      img: './images4.jfif',
      desc: `Rich look, good for office goers`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'AVAILABLE ITEMS',
      price: 22.99,
      img: './images5.jfif',
      desc: `Greyish white, full tee, summer wear`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'AVAILABLE ITEMS',
      price: 18.99,
      img: './images6.jfif',
      desc: `Black coat, goes well with shirt or tees`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'AVAILABLE ITEMS',
      price: 8.99,
      img: './images7.jfif',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'AVAILABLE ITEMS',
      price: 12.99,
      img: './images8.jfif',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'AVAILABLE ITEMS',
      price: 16.99,
      img: './images9.jfif',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: 'grey t-shirt',
      category: 'AVAILABLE ITEMS',
      price: 16.99,
      img: './images1.jfif',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    }
  ];
  export default items;