const items = [
    {
      id: 1,
      title: 'classic full tee',
      category: 'AVAILABLE ITEMS',
      price: 15.99,
      img: './images.jfif',
      desc: `Made from cotton,good as a party wear `,
    },
    {
      id: 2,
      title: 'winter jacket',
      category: 'AVAILABLE ITEMS',
      price: 13.99,
      img: './images2.jfif',
      desc: `best for cold climates, goes well with boots `,
    },
    {
      id: 3,
      title: 'grey and black coat',
      category: 'AVAILABLE ITEMS',
      price: 6.99,
      img: './images3.jfif',
      desc: `best for cold climates, goes well with boots.`,
    },
    {
      id: 4,
      title: 'khaki winter jacket',
      category: 'AVAILABLE ITEMS',
      price: 20.99,
      img: './images4.jfif',
      desc: `Rich look, good for office goers `,
    },
    {
      id: 5,
      title: 'full tees',
      category: 'AVAILABLE ITEMS',
      price: 22.99,
      img: './images5.jfif',
      desc: `Greyish white, full tee, summer wear `,
    },
    {
      id: 6,
      title: 'black coat',
      category: 'AVAILABLE ITEMS',
      price: 18.99,
      img: './images6.jfif',
      desc: `Black coat, goes well with shirt or tees`,
    },
    {
      id: 7,
      title: 'Red jersey wear',
      category: 'AVAILABLE ITEMS',
      price: 8.99,
      img: './images7.jfif',
      desc: `Bright Red color, good for sporting events`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'AVAILABLE ITEMS',
      price: 12.99,
      img: './images8.jfif',
      desc: `Military green tee,long lasting, rough use`,
    },
    {
      id: 9,
      title: 'sky-blue shirt',
      category: 'AVAILABLE ITEMS',
      price: 16.99,
      img: './images9.jfif',
      desc: `Best summer wear, good party wear`,
    },
    {
      id: 10,
      title: 'grey t-shirt',
      category: 'AVAILABLE ITEMS',
      price: 16.99,
      img: './images1.jfif',
      desc: `synthetic,highly durable`,
    }
  ];
  export default items;