const items = [
    {
      id: 1,
      title: 'classic summer shirt',
      category: 'AVAILABLE ITEMS',
      price: 15.99,
      img: './images.jfif',
      desc: `Made from cotton,good as a party wear,highly durable,wear and tear tested`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'AVAILABLE ITEMS',
      price: 13.99,
      img: './images2.jfif',
      desc: `best for cold climates, goes well with boots,highly durable,wear and tear tested`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'AVAILABLE ITEMS',
      price: 6.99,
      img: './images3.jfif',
      desc: `best for cold climates, goes well with boots,highly durable,wear and tear tested`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'AVAILABLE ITEMS',
      price: 20.99,
      img: './images4.jfif',
      desc: `Rich look, good for office goers,highly durable,wear and tear tested`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'AVAILABLE ITEMS',
      price: 22.99,
      img: './images5.jfif',
      desc: `Greyish white, full tee, summer wear,highly durable,wear and tear tested`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'AVAILABLE ITEMS',
      price: 18.99,
      img: './images6.jfif',
      desc: `Black coat, goes well with shirt or tees,highly durable,wear and tear tested`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'AVAILABLE ITEMS',
      price: 8.99,
      img: './images7.jfif',
      desc: `Bright Red color, good for sporting events,highly durable,wear and tear tested`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'AVAILABLE ITEMS',
      price: 12.99,
      img: './images8.jfif',
      desc: `Military green tee,long lasting, rough use,highly durable,wear and tear tested `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'AVAILABLE ITEMS',
      price: 16.99,
      img: './images9.jfif',
      desc: `Best summer wear, good party wear,sky blue shirt,highly durable,wear and tear tested`,
    },
    {
      id: 10,
      title: 'grey t-shirt',
      category: 'AVAILABLE ITEMS',
      price: 16.99,
      img: './images1.jfif',
      desc: `synthetic,highly durable,nice grey t-shirt,highly durable,wear and tear tested`,
    }
  ];
  export default items;